sudo: false

language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  global:
    - DEFAULT_PYTHON=2.7
    - DEFAULT_DJANGO=1.8
  matrix:
    - DJANGO=1.6
    - DJANGO=1.7
    - DJANGO=1.8

matrix:
  exclude:
    - python: 3.4
      env: DJANGO=1.6
    - python: 3.5
      env: DJANGO=1.6
    - python: 3.5
      env: DJANGO=1.7
  include:
    - python: 2.7
      env: DJANGO=1.4
    - python: 2.7
      env: DJANGO=1.5
    - python: 2.7
      env: FLAKE8=1

before_install:
  - if [ -z "$DJANGO" ]; then export DJANGO=$DEFAULT_DJANGO; fi
  - if [[ -z "$FLAKE8" && $TRAVIS_PYTHON_VERSION == $DEFAULT_PYTHON && $DJANGO == $DEFAULT_DJANGO ]]; then export COVERAGE=1; fi

install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements.txt
  - if [[ $FLAKE8 ]]; then pip install flake8; fi
  - if [[ $COVERAGE ]]; then pip install coverage==3.7.1 python-coveralls; fi

script:
  - if [[ $FLAKE8 ]]; then flake8; fi
  - if [[ $COVERAGE ]]; then coverage run --source=multi_import runtests.py; fi
  - if [[ -z "$FLAKE8" && -z "$COVERAGE" ]]; then ./runtests.py; fi

after_success:
  - if [[ $COVERAGE ]]; then coveralls; fi
