sudo: false

dist: xenial

language: python

matrix:
  include:
    - python: 3.6
      env: LINT=1 DJANGO=1.11
    - python: 2.7
      env: DJANGO=1.11
    - python: 3.6
      env: DJANGO=1.11
    - python: 3.6
      env: DJANGO=2.0
    - python: 3.6
      env: DJANGO=2.1
    - python: 3.6
      env: DJANGO=2.2
    - python: 3.6
      env: DJANGO=3.0
    - python: 3.7
      env: DJANGO=1.11
    - python: 3.7
      env: DJANGO=2.0
    - python: 3.7
      env: DJANGO=2.1
    - python: 3.7
      env: DJANGO=2.2
    - python: 3.7
      env: DJANGO=3.0

before_install:
  - if [ -z "$DJANGO" ]; then export DJANGO=$DEFAULT_DJANGO; fi
  - if [[ -z "$LINT" && $TRAVIS_PYTHON_VERSION == $DEFAULT_PYTHON && $DJANGO == $DEFAULT_DJANGO ]]; then export COVERAGE=1; fi

install:
  - make init
  - pip install Django==$DJANGO
  - if [[ $COVERAGE ]]; then pip install python-coveralls; fi

script:
  - if [[ $LINT ]]; then make lint; fi
  - if [[ $COVERAGE ]]; then make coverage; fi
  - if [[ -z "$LINT" && -z "$COVERAGE" ]]; then make test; fi

after_success:
  - if [[ $COVERAGE ]]; then coveralls; fi
