sudo: false

dist: xenial

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  global:
    - DEFAULT_PYTHON=2.7
    - DEFAULT_DJANGO=1.11.20
  matrix:
    - DJANGO=1.11.20

matrix:
  include:
    - python: 2.7
      env: LINT=1

before_install:
  - if [ -z "$DJANGO" ]; then export DJANGO=$DEFAULT_DJANGO; fi
  - if [[ -z "$LINT" && $TRAVIS_PYTHON_VERSION == $DEFAULT_PYTHON && $DJANGO == $DEFAULT_DJANGO ]]; then export COVERAGE=1; fi

install:
  - pip install -q Django==$DJANGO
  - make init
  - if [[ $COVERAGE ]]; then pip install python-coveralls; fi

script:
  - if [[ $LINT ]]; then make lint; fi
  - if [[ $COVERAGE ]]; then make coverage; fi
  - if [[ -z "$LINT" && -z "$COVERAGE" ]]; then make test; fi

after_success:
  - if [[ $COVERAGE ]]; then coveralls; fi
