sudo: false

language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8

matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.4
    - python: 3.3
      env: DJANGO=1.5
    - python: 3.3
      env: DJANGO=1.6

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors

script:
  - ./runtests.py
