sudo: false
language: python
jobs:
  include:
      - if: tag IS blank
        python: "3.6"
        env: DJANGO=3.0
      - if: tag IS blank
        python: "3.8"
        env: DJANGO=3.0
install:
  - pip install -q Django~=$DJANGO python-coveralls
  - make init
script:
  - make lint
  - make coverage
  - make test
after_success:
  - coveralls
